# -*- coding: utf-8 -*-
"""Exp_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I3VsfF903uMJxMzq1PjORghhjgdmWJm1
"""

# To study Convolutional Neural Network and Recurrent Neural Network.

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    MaxPooling2D((2,2)),
    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D((2,2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

model.summary()